# Generated by Django 4.2.9 on 2024-04-12 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("permalink", models.CharField(max_length=12, unique=True)),
                ("update_date", models.DateTimeField(verbose_name="Last Updated")),
                (
                    "create_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="First Published"
                    ),
                ),
                ("bodytext", models.TextField(blank=True, verbose_name="Page Content")),
                (
                    "pic",
                    models.ImageField(
                        blank=True, default="placeholder.png", upload_to=""
                    ),
                ),
            ],
        ),
    ]
