# Generated by Django 4.2.9 on 2024-04-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Genres", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist", old_name="name", new_name="artist_name",
        ),
        migrations.RenameField(
            model_name="userprofile", old_name="user", new_name="user_name",
        ),
        migrations.DeleteModel(name="Channel",),
    ]
