# Generated by Django 4.2.9 on 2024-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Genres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="youtube_video_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
