# Generated by Django 4.2.9 on 2024-04-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Genres", "0002_artist_youtube_video_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("link", models.URLField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Genres.artist"
                    ),
                ),
            ],
        ),
    ]
