# Generated by Django 4.2.9 on 2024-04-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Genres", "0002_rename_name_artist_artist_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist", old_name="artist_name", new_name="name",
        ),
        migrations.RemoveField(model_name="artist", name="bio",),
        migrations.RemoveField(model_name="artist", name="image",),
    ]
