# Generated by Django 5.0.4 on 2024-04-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0004_artist_youtube_video_id_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='youtube_video_id',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=11)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Genres.artist')),
            ],
        ),
    ]
