# Generated by Django 4.2.9 on 2024-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Genres", "0004_youtubechannel_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubechannel",
            name="video_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
