# Generated by Django 5.0.4 on 2024-04-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0005_remove_artist_youtube_video_id_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
