# Generated by Django 4.2.9 on 2024-04-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Genres", "0006_remove_youtubechannel_video_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubechannel",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Genres.artist"
            ),
        ),
    ]
