# Generated by Django 5.0.3 on 2024-04-03 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Last Updated'),
            preserve_default=False,
        ),
    ]
