# Generated by Django 5.0.3 on 2024-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_create_date_page_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pic',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
    ]
